import { LevelData } from '../types';

export const LEVELS_DATA: LevelData[] = [
  // ==========================================
  // LEVEL 1: الحديقة (The Garden)
  // ==========================================
  {
    id: 1,
    name: 'الحديقة',
    theme: {
      name: 'الحديقة',
      subtitle: 'حيث بدأت الحكاية',
      description: 'ظلال هادئة ونسيم عذب، حيث ينطلق المسار وتستقر أولى الذكريات.',
      skyTop: '#D4EBF8',
      skyBottom: '#F2F9FF',
      cloudColor: 'rgba(255, 255, 255, 0.85)',
      cloudShadow: 'rgba(210, 230, 245, 0.5)',
      accentColor: '#4ADE80',
      particleColor: '#FDE047',
      weatherType: 'CLEAR',
    },
    width: 8100,
    height: 700,
    playerStart: { x: 120, y: 350 },
    targetWindow: { x: 7750, y: 350 },
    windZones: [
      {
        id: 'w1_1',
        x: 1200,
        y: 200,
        width: 450,
        height: 350,
        direction: 'UP',
        strength: 0.8,
      },
      {
        id: 'w1_2',
        x: 2700,
        y: 150,
        width: 500,
        height: 400,
        direction: 'FORWARD',
        strength: 1.1,
      },
      {
        id: 'w1_3',
        x: 4150,
        y: 200,
        width: 450,
        height: 350,
        direction: 'UP',
        strength: 0.8,
      },
      {
        id: 'w1_4',
        x: 5650,
        y: 150,
        width: 500,
        height: 400,
        direction: 'FORWARD',
        strength: 1.1,
      },
    ],
    obstacles: [
      // Few gentle branches and birds, well spaced along the path
      {
        id: 'o1_1',
        type: 'BRANCH',
        x: 850,
        y: 100,
        width: 140,
        height: 120,
      },
      {
        id: 'o1_2',
        type: 'BRANCH',
        x: 1600,
        y: 480,
        width: 160,
        height: 140,
      },
      {
        id: 'o1_3',
        type: 'BIRD',
        x: 1800,
        y: 280,
        width: 35,
        height: 25,
        speed: 0.6,
        animOffset: 0,
      },
      {
        id: 'o1_4',
        type: 'BRANCH',
        x: 2900,
        y: 120,
        width: 180,
        height: 130,
      },
      {
        id: 'o1_5',
        type: 'BIRD',
        x: 3200,
        y: 380,
        width: 35,
        height: 25,
        speed: 0.7,
        animOffset: 1.5,
      },
      {
        id: 'o1_6',
        type: 'BRANCH',
        x: 4350,
        y: 470,
        width: 150,
        height: 140,
      },
      {
        id: 'o1_7',
        type: 'BIRD',
        x: 4650,
        y: 250,
        width: 35,
        height: 25,
        speed: 0.6,
        animOffset: 0.8,
      },
      {
        id: 'o1_8',
        type: 'BRANCH',
        x: 5850,
        y: 120,
        width: 170,
        height: 130,
      },
      {
        id: 'o1_9',
        type: 'BRANCH',
        x: 6300,
        y: 470,
        width: 150,
        height: 140,
      },
      {
        id: 'o1_10',
        type: 'BIRD',
        x: 7200,
        y: 360,
        width: 35,
        height: 25,
        speed: 0.7,
        animOffset: 2.1,
      },
    ],
    shards: [
      {
        id: 's1_1',
        x: 450,
        y: 350,
        text: 'في ظلال هذا البستان، أدركتُ معنى أن يكون للمرء مأوى يألفه ويسكن إليه.',
        collected: false,
        order: 1,
      },
      {
        id: 's1_2',
        x: 2100,
        y: 240,
        text: 'كل زاوية هنا تحتفظ بأثرٍ طيّب من خطواتنا الهادئة وأحاديثنا الصادقة.',
        collected: false,
        order: 2,
      },
      {
        id: 's1_3',
        x: 3500,
        y: 340,
        text: 'كانت اليد التي أمسكت بي تُشعرني بأن الأمان قرار نتخذه معًا.',
        collected: false,
        order: 3,
      },
      {
        id: 's1_4',
        x: 4950,
        y: 260,
        text: 'حين باغتتني الرياح بالابتعاد، علمتُ أن المسافات لا تنال من ثبات العهد.',
        collected: false,
        order: 4,
      },
      {
        id: 's1_5',
        x: 6550,
        y: 320,
        text: 'البوصلة تظل دومًا مشدودة نحو البداية.',
        collected: false,
        order: 5,
      },
    ],
    checkpoints: [
      { id: 'cp1_1', x: 200, y: 350, activated: true },
      { id: 'cp1_2', x: 2800, y: 350, activated: false },
      { id: 'cp1_3', x: 5750, y: 350, activated: false },
    ],
    sceneryElements: {
      hills: [
        { x: 300, height: 180, width: 600, color: '#BBF7D0' },
        { x: 1200, height: 220, width: 700, color: '#86EFAC' },
        { x: 2100, height: 190, width: 650, color: '#BBF7D0' },
        { x: 3000, height: 210, width: 700, color: '#86EFAC' },
        { x: 3900, height: 190, width: 650, color: '#BBF7D0' },
        { x: 4800, height: 220, width: 700, color: '#86EFAC' },
        { x: 5700, height: 200, width: 650, color: '#BBF7D0' },
        { x: 6600, height: 220, width: 700, color: '#86EFAC' },
        { x: 7400, height: 190, width: 650, color: '#BBF7D0' },
      ],
      trees: [
        { x: 250, y: 550, height: 160, color: '#16A34A' },
        { x: 750, y: 560, height: 180, color: '#15803D' },
        { x: 1400, y: 540, height: 170, color: '#16A34A' },
        { x: 2300, y: 550, height: 190, color: '#15803D' },
        { x: 3200, y: 560, height: 175, color: '#16A34A' },
        { x: 4100, y: 540, height: 185, color: '#15803D' },
        { x: 5000, y: 550, height: 170, color: '#16A34A' },
        { x: 5900, y: 560, height: 190, color: '#15803D' },
        { x: 6800, y: 540, height: 175, color: '#16A34A' },
        { x: 7550, y: 550, height: 180, color: '#15803D' },
      ],
    },
  },

  // ==========================================
  // LEVEL 2: الشارع (The Street / Old City)
  // ==========================================
  {
    id: 2,
    name: 'الشارع',
    theme: {
      name: 'الشارع',
      subtitle: 'أفق العبور والدروب المألوفة',
      description: 'امتداد الأسطح وأضواء الغروب، حيث تتجلى غاية المسير.',
      skyTop: '#FED7AA',
      skyBottom: '#FFF7ED',
      cloudColor: 'rgba(255, 237, 213, 0.85)',
      cloudShadow: 'rgba(251, 146, 60, 0.3)',
      accentColor: '#FB923C',
      particleColor: '#F97316',
      weatherType: 'BREEZY',
    },
    width: 8100,
    height: 700,
    playerStart: { x: 120, y: 350 },
    targetWindow: { x: 7760, y: 330 },
    windZones: [
      {
        id: 'w2_1',
        x: 1100,
        y: 100,
        width: 450,
        height: 500,
        direction: 'DOWN',
        strength: 0.7,
      },
      {
        id: 'w2_2',
        x: 2600,
        y: 100,
        width: 450,
        height: 500,
        direction: 'UP',
        strength: 0.9,
      },
      {
        id: 'w2_3',
        x: 4000,
        y: 150,
        width: 450,
        height: 400,
        direction: 'FORWARD',
        strength: 1.2,
      },
      {
        id: 'w2_4',
        x: 5500,
        y: 100,
        width: 450,
        height: 500,
        direction: 'UP',
        strength: 0.8,
      },
    ],
    obstacles: [
      {
        id: 'o2_1',
        type: 'POWER_LINE',
        x: 850,
        y: 280,
        width: 250,
        height: 16,
      },
      {
        id: 'o2_2',
        type: 'CHIMNEY',
        x: 1350,
        y: 440,
        width: 70,
        height: 180,
      },
      {
        id: 'o2_3',
        type: 'POWER_LINE',
        x: 2350,
        y: 220,
        width: 280,
        height: 16,
      },
      {
        id: 'o2_4',
        type: 'BIRD',
        x: 2750,
        y: 240,
        width: 35,
        height: 25,
        speed: 0.9,
      },
      {
        id: 'o2_5',
        type: 'CHIMNEY',
        x: 3750,
        y: 460,
        width: 80,
        height: 160,
      },
      {
        id: 'o2_6',
        type: 'POWER_LINE',
        x: 4250,
        y: 380,
        width: 300,
        height: 16,
      },
      {
        id: 'o2_7',
        type: 'POWER_LINE',
        x: 5200,
        y: 220,
        width: 260,
        height: 16,
      },
      {
        id: 'o2_8',
        type: 'CHIMNEY',
        x: 5800,
        y: 450,
        width: 75,
        height: 170,
      },
      {
        id: 'o2_9',
        type: 'BIRD',
        x: 6700,
        y: 260,
        width: 35,
        height: 25,
        speed: 0.9,
      },
      {
        id: 'o2_10',
        type: 'POWER_LINE',
        x: 7200,
        y: 220,
        width: 260,
        height: 16,
      },
    ],
    shards: [
      {
        id: 's2_1',
        x: 450,
        y: 360,
        text: 'من هذا العلو، تبدو تفاصيل الأماكن أكثر اتساعًا، ويتضح تسلسل الحكاية.',
        collected: false,
        order: 1,
      },
      {
        id: 's2_2',
        x: 1950,
        y: 380,
        text: 'المعالم التي عهدناها شاهدةٌ على أن للمودة موطنًا لا تُنسى ملامحه.',
        collected: false,
        order: 2,
      },
      {
        id: 's2_3',
        x: 3430,
        y: 300,
        text: 'أسراب الطيور العابرة تُدرك بفطرتها أن لكل جناحٍ غاية.',
        collected: false,
        order: 3,
      },
      {
        id: 's2_4',
        x: 4780,
        y: 240,
        text: 'بين تشابك الطرق وتقاطع المسارات، يستدلّ المرء بصدق مقصده ونقاء مبتغاه.',
        collected: false,
        order: 4,
      },
      {
        id: 's2_5',
        x: 6260,
        y: 340,
        text: 'المدى فسيح ومتشعب، غير أن وضوح الهدف كفيلٌ باختصار كل اغتراب.',
        collected: false,
        order: 5,
      },
    ],
    checkpoints: [
      { id: 'cp2_1', x: 200, y: 350, activated: true },
      { id: 'cp2_2', x: 2700, y: 350, activated: false },
      { id: 'cp2_3', x: 5500, y: 350, activated: false },
    ],
    sceneryElements: {
      buildings: [
        { x: 200, y: 480, width: 220, height: 220, color: '#FDBA74', windows: true },
        { x: 600, y: 440, width: 260, height: 260, color: '#FED7AA', windows: true },
        { x: 1100, y: 500, width: 240, height: 200, color: '#FB923C', windows: true },
        { x: 1600, y: 460, width: 280, height: 240, color: '#FDBA74', windows: true },
        { x: 2200, y: 480, width: 230, height: 220, color: '#FED7AA', windows: true },
        { x: 2800, y: 430, width: 300, height: 270, color: '#FB923C', windows: true },
        { x: 3500, y: 470, width: 250, height: 230, color: '#FDBA74', windows: true },
        { x: 4100, y: 450, width: 260, height: 250, color: '#FED7AA', windows: true },
        { x: 4700, y: 480, width: 270, height: 220, color: '#FDBA74', windows: true },
        { x: 5300, y: 440, width: 280, height: 260, color: '#FED7AA', windows: true },
        { x: 6000, y: 460, width: 250, height: 240, color: '#FB923C', windows: true },
        { x: 6700, y: 450, width: 290, height: 250, color: '#FDBA74', windows: true },
        { x: 7400, y: 470, width: 260, height: 230, color: '#FED7AA', windows: true },
      ],
    },
  },

  // ==========================================
  // LEVEL 3: العاصفة (The Storm)
  // ==========================================
  {
    id: 3,
    name: 'العاصفة',
    theme: {
      name: 'العاصفة',
      subtitle: 'اختبار الصمود والإرادة',
      description: 'رياح متلاطمة وقطرات غيث متتابعة تصقل العزم وتزيد من رسوخ الخطى.',
      skyTop: '#1E293B',
      skyBottom: '#475569',
      cloudColor: 'rgba(30, 41, 59, 0.9)',
      cloudShadow: 'rgba(15, 23, 42, 0.7)',
      accentColor: '#38BDF8',
      particleColor: '#60A5FA',
      weatherType: 'RAIN_STORM',
    },
    width: 8500,
    height: 700,
    playerStart: { x: 120, y: 350 },
    targetWindow: { x: 8140, y: 320 },
    windZones: [
      {
        id: 'w3_1',
        x: 1000,
        y: 80,
        width: 450,
        height: 550,
        direction: 'DOWN',
        strength: 1.0,
      },
      {
        id: 'w3_2',
        x: 2700,
        y: 80,
        width: 450,
        height: 550,
        direction: 'UP',
        strength: 1.1,
      },
      {
        id: 'w3_3',
        x: 4300,
        y: 100,
        width: 450,
        height: 500,
        direction: 'DOWN',
        strength: 0.9,
      },
      {
        id: 'w3_4',
        x: 5800,
        y: 100,
        width: 500,
        height: 500,
        direction: 'FORWARD',
        strength: 1.3,
      },
      {
        id: 'w3_5',
        x: 7100,
        y: 80,
        width: 450,
        height: 550,
        direction: 'UP',
        strength: 1.0,
      },
    ],
    obstacles: [
      {
        id: 'o3_1',
        type: 'STORM_CLOUD',
        x: 950,
        y: 140,
        width: 140,
        height: 80,
      },
      {
        id: 'o3_2',
        type: 'LIGHTNING_NODE',
        x: 1450,
        y: 320,
        width: 50,
        height: 50,
      },
      {
        id: 'o3_3',
        type: 'STORM_CLOUD',
        x: 2500,
        y: 460,
        width: 160,
        height: 90,
      },
      {
        id: 'o3_4',
        type: 'LIGHTNING_NODE',
        x: 3000,
        y: 220,
        width: 50,
        height: 50,
      },
      {
        id: 'o3_5',
        type: 'STORM_CLOUD',
        x: 4100,
        y: 150,
        width: 150,
        height: 85,
      },
      {
        id: 'o3_6',
        type: 'LIGHTNING_NODE',
        x: 4600,
        y: 380,
        width: 50,
        height: 50,
      },
      {
        id: 'o3_7',
        type: 'STORM_CLOUD',
        x: 5500,
        y: 440,
        width: 170,
        height: 95,
      },
      {
        id: 'o3_8',
        type: 'LIGHTNING_NODE',
        x: 6050,
        y: 250,
        width: 50,
        height: 50,
      },
      {
        id: 'o3_9',
        type: 'STORM_CLOUD',
        x: 7000,
        y: 160,
        width: 160,
        height: 90,
      },
      {
        id: 'o3_10',
        type: 'LIGHTNING_NODE',
        x: 7500,
        y: 350,
        width: 50,
        height: 50,
      },
    ],
    shards: [
      {
        id: 's3_1',
        x: 450,
        y: 320,
        text: 'حتى أعتى الرياح لا تدوم إلى الأبد، وفي عمق العاصفة يولد الصفاء.',
        collected: false,
        order: 1,
      },
      {
        id: 's3_2',
        x: 2100,
        y: 220,
        text: 'مقاومة التيارات العاتية تمنح العزم صلابة، وتعلّمنا كيف نحافظ على وجهتنا.',
        collected: false,
        order: 2,
      },
      {
        id: 's3_3',
        x: 3610,
        y: 380,
        text: 'في قلب الضباب الكثيف، يظل اليقين سراجًا ينير المسار دون تردد.',
        collected: false,
        order: 3,
      },
      {
        id: 's3_4',
        x: 5090,
        y: 220,
        text: 'الغيوم الداكنة سرعان ما تنجلي، كاشفةً عن أفقٍ أرحب يفيض بالنور.',
        collected: false,
        order: 4,
      },
      {
        id: 's3_5',
        x: 6570,
        y: 320,
        text: 'كل ميلٍ نقطعه في وجه العواصف هو خطوةٌ راسخة نحو مرافئ الطمأنينة.',
        collected: false,
        order: 5,
      },
    ],
    checkpoints: [
      { id: 'cp3_1', x: 200, y: 350, activated: true },
      { id: 'cp3_2', x: 2850, y: 350, activated: false },
      { id: 'cp3_3', x: 5850, y: 350, activated: false },
    ],
    sceneryElements: {},
  },

  // ==========================================
  // LEVEL 4: الليل (The Night)
  // ==========================================
  {
    id: 4,
    name: 'الليل',
    theme: {
      name: 'الليل',
      subtitle: 'سكينة الدجى وهدى النجوم',
      description: 'سماء حالكة تتلألأ فيها النجوم، حيث يهدأ الصخب وتتجلى الأفكار في صفاء تام.',
      skyTop: '#0F172A',
      skyBottom: '#1E1B4B',
      cloudColor: 'rgba(51, 65, 85, 0.6)',
      cloudShadow: 'rgba(30, 27, 75, 0.5)',
      accentColor: '#C084FC',
      particleColor: '#FDE047',
      weatherType: 'STARRY',
    },
    width: 8600,
    height: 700,
    playerStart: { x: 120, y: 350 },
    targetWindow: { x: 8280, y: 340 },
    windZones: [
      {
        id: 'w4_1',
        x: 1100,
        y: 120,
        width: 450,
        height: 480,
        direction: 'UP',
        strength: 0.7,
      },
      {
        id: 'w4_2',
        x: 2800,
        y: 120,
        width: 450,
        height: 480,
        direction: 'FORWARD',
        strength: 1.1,
      },
      {
        id: 'w4_3',
        x: 4450,
        y: 120,
        width: 450,
        height: 480,
        direction: 'UP',
        strength: 0.8,
      },
      {
        id: 'w4_4',
        x: 6000,
        y: 120,
        width: 500,
        height: 480,
        direction: 'FORWARD',
        strength: 1.1,
      },
    ],
    obstacles: [
      {
        id: 'o4_1',
        type: 'KITE',
        x: 800,
        y: 220,
        width: 60,
        height: 70,
        animOffset: 0.2,
      },
      {
        id: 'o4_2',
        type: 'KITE',
        x: 1400,
        y: 400,
        width: 65,
        height: 75,
        animOffset: 1.1,
      },
      {
        id: 'o4_3',
        type: 'KITE',
        x: 2500,
        y: 190,
        width: 60,
        height: 70,
        animOffset: 2.3,
      },
      {
        id: 'o4_4',
        type: 'KITE',
        x: 3200,
        y: 390,
        width: 70,
        height: 80,
        animOffset: 0.8,
      },
      {
        id: 'o4_5',
        type: 'KITE',
        x: 4300,
        y: 210,
        width: 65,
        height: 75,
        animOffset: 1.7,
      },
      {
        id: 'o4_6',
        type: 'KITE',
        x: 5000,
        y: 380,
        width: 60,
        height: 70,
        animOffset: 3.1,
      },
      {
        id: 'o4_7',
        type: 'KITE',
        x: 6000,
        y: 200,
        width: 65,
        height: 75,
        animOffset: 0.5,
      },
      {
        id: 'o4_8',
        type: 'KITE',
        x: 7200,
        y: 360,
        width: 60,
        height: 70,
        animOffset: 2.0,
      },
    ],
    shards: [
      {
        id: 's4_1',
        x: 450,
        y: 330,
        text: 'في سكون الليل يتوارى ضجيج العالم، ولا يتبقى سوى صوت الحقيقة الداخلي.',
        collected: false,
        order: 1,
      },
      {
        id: 's4_2',
        x: 2020,
        y: 240,
        text: 'النجوم في عليائها تذكّرنا بأن الضوء الأصدق هو الذي ينبعث في أشد الأوقات حلكة.',
        collected: false,
        order: 2,
      },
      {
        id: 's4_3',
        x: 3750,
        y: 340,
        text: 'التحليق وسط هذا المدى الصامت يعلّم النفس فضيلة الصبر وحكمة الانتظار.',
        collected: false,
        order: 3,
      },
      {
        id: 's4_4',
        x: 5230,
        y: 260,
        text: 'الظلام ليس نهاية المطاف، بل هو المعبر الهادئ نحو فجرٍ جديد.',
        collected: false,
        order: 4,
      },
      {
        id: 's4_5',
        x: 6710,
        y: 300,
        text: 'حين تسكن الرياح ويقترب انبلاج الصبح، تكتمل ملامح الرحلة ومعانيها العميقة.',
        collected: false,
        order: 5,
      },
    ],
    checkpoints: [
      { id: 'cp4_1', x: 200, y: 350, activated: true },
      { id: 'cp4_2', x: 2900, y: 350, activated: false },
      { id: 'cp4_3', x: 6000, y: 350, activated: false },
    ],
    sceneryElements: {
      stars: [
        { x: 100, y: 80, size: 2, opacity: 0.8 },
        { x: 400, y: 140, size: 3, opacity: 0.9 },
        { x: 800, y: 90, size: 2, opacity: 0.7 },
        { x: 1200, y: 160, size: 4, opacity: 1.0 },
        { x: 1650, y: 100, size: 2.5, opacity: 0.85 },
        { x: 2100, y: 70, size: 3, opacity: 0.9 },
        { x: 2600, y: 130, size: 2, opacity: 0.75 },
        { x: 3100, y: 90, size: 3.5, opacity: 1.0 },
        { x: 3600, y: 150, size: 2, opacity: 0.8 },
        { x: 4100, y: 80, size: 3, opacity: 0.9 },
        { x: 4600, y: 120, size: 2.5, opacity: 0.85 },
        { x: 5200, y: 90, size: 4, opacity: 1.0 },
        { x: 5750, y: 140, size: 2, opacity: 0.8 },
        { x: 6300, y: 80, size: 3, opacity: 0.9 },
        { x: 6900, y: 110, size: 2.5, opacity: 0.85 },
        { x: 7500, y: 90, size: 3.5, opacity: 1.0 },
        { x: 8100, y: 130, size: 2, opacity: 0.8 },
      ],
    },
  },

  // ==========================================
  // LEVEL 5: النافذة (The Window / Golden Dawn)
  // ==========================================
  {
    id: 5,
    name: 'النافذة',
    theme: {
      name: 'النافذة',
      subtitle: 'بشائر الوصول ومرافئ الأمان',
      description: 'أشعة الفجر الذهبية تبدد وحشة الغياب، معلنةً اكتمال الدائرة وبلوغ المقصد.',
      skyTop: '#FEF08A',
      skyBottom: '#FFE4E6',
      cloudColor: 'rgba(255, 255, 255, 0.92)',
      cloudShadow: 'rgba(254, 205, 211, 0.5)',
      accentColor: '#F43F5E',
      particleColor: '#FB7185',
      weatherType: 'GOLDEN_DAWN',
    },
    width: 8300,
    height: 700,
    playerStart: { x: 120, y: 350 },
    targetWindow: { x: 7980, y: 350 }, // Warm glowing attic window
    windZones: [
      {
        id: 'w5_1',
        x: 350,
        y: 100,
        width: 7500,
        height: 500,
        direction: 'FORWARD',
        strength: 0.85,
      },
    ],
    // Obstacle-free! Poetic final approach
    obstacles: [],
    shards: [
      {
        id: 's5_1',
        x: 450,
        y: 350,
        text: 'نسيم الصباح العليل يمنح الخطى فرصةً جديدة للبدء من جديد.',
        collected: false,
        order: 1,
      },
      {
        id: 's5_2',
        x: 1850,
        y: 320,
        text: 'تلوح ملامح المكان القديم في الأفق، دافئةً كما تركناها أول مرة.',
        collected: false,
        order: 2,
      },
      {
        id: 's5_3',
        x: 3330,
        y: 340,
        text: 'النافذة المفتوحة على سكون الفجر تؤكد أن الانتظار لم يكن يومًا سرابًا.',
        collected: false,
        order: 3,
      },
      {
        id: 's5_4',
        x: 4900,
        y: 330,
        text: 'حين يلتقي السعي بالوصول، تغدو كل مشقة خضناها فصلًا يستحق الذكرى.',
        collected: false,
        order: 4,
      },
      {
        id: 's5_5',
        x: 6470,
        y: 350,
        text: 'ها قد عاد الخيط إلى حيث بدأ.. واكتملت الرحلة بسلامٍ وطمأنينة.',
        collected: false,
        order: 5,
      },
    ],
    checkpoints: [
      { id: 'cp5_1', x: 200, y: 350, activated: true },
      { id: 'cp5_2', x: 4100, y: 350, activated: false },
    ],
    sceneryElements: {
      buildings: [
        { x: 7700, y: 250, width: 320, height: 450, color: '#FBCFE8', windows: true },
      ],
      trees: [
        { x: 1200, y: 530, height: 170, color: '#34D399' },
        { x: 2700, y: 520, height: 180, color: '#10B981' },
        { x: 4200, y: 530, height: 175, color: '#34D399' },
        { x: 5700, y: 520, height: 185, color: '#10B981' },
        { x: 7200, y: 520, height: 180, color: '#34D399' },
      ],
    },
  },
];
